name: Firebase Trigger
description: Update a field in your firebase database
author: Vinod Kumar T
inputs:
  credentials:
    description: Admin credentials json for connecting to application
    required: true
  databaseUrl:
    description: URL to the database you want to connect to
    required: true
  projName:
    description: Name of the project to be used in path
    required: true
branding:
  icon: 'activity'
  color: 'gray-dark'
runs:
  using: node12
  main: dist/index.js